### PR TITLE
Fixing Markdown Errors For GH Viewing

### PR DESCRIPTION
**Pull request by christopherhein**
**Why:**

* Allows Github to preview the CoC properly

### CODE REVIEW

**Comment by christopherhein** [comment]
Awesome!

**Comment by christopherhein** [comment]
Who manages merging these?

**Comment by hugovk** [comment]
Ping @thaJeztah

**Comment by thaJeztah** [comment]
Oh, whoops, but I think I fixed these in another pull request, and forgot to check existing ones; can you check on current master, because I think they're all fixed already 😅

**Comment by hugovk** [comment]
Looks good in https://github.com/docker/code-of-conduct/commit/eebd0bdb5bc988b1b67c43588f93dbf8f5d2ec5d, thanks!

**Comment by thaJeztah** [comment]
Let me close this PR; apologies that I didn't see it before opening mine 😊, thanks so much for contributing!

**Comment by christopherhein** [comment]
Sweet! Thanks @thaJeztah

**Pull request closed without merging**
